# Generated by Django 2.1.2 on 2018-10-24 12:02

import Account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RBCUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='username')),
                ('first_name', models.CharField(max_length=50, verbose_name='first_name')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='middle_name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='last_name')),
                ('year', models.IntegerField(choices=[(2, '2nd'), (3, '3rd'), (4, '4th')], null=True, verbose_name='year')),
                ('room_number', models.IntegerField(choices=[(101, '101'), (102, '102'), (103, '103'), (202, '202'), (211, '211')], null=True, verbose_name='room_number')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('staff', models.BooleanField(default=False, verbose_name='staff')),
                ('admin', models.BooleanField(default=False, verbose_name='admin')),
                ('authenticated', models.BooleanField(default=False, verbose_name='authenticated')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='date_joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', Account.models.RBCUserManager()),
            ],
        ),
    ]
