# Generated by Django 2.1.2 on 2018-10-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rbcuser',
            name='date_joined',
        ),
    ]
