# Generated by Django 2.1.2 on 2018-11-25 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbcuser',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_joined'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rbcuser',
            name='room_number',
            field=models.IntegerField(choices=[(101, '101'), (102, '102'), (103, '103'), (104, '104'), (105, '105'), (201, '201'), (202, '202'), (203, '203'), (204, '204'), (205, '205'), (207, '207'), (208, '208'), (209, '209'), (210, '210'), (211, '211'), (212, '212'), (301, '301'), (302, '302'), (303, '303'), (304, '304'), (305, '305'), (306, '306'), (307, '307'), (308, '308'), (309, '309'), (310, '310'), (311, '311'), (312, '312')], null=True, verbose_name='room_number'),
        ),
    ]
