# Generated by Django 2.1.2 on 2018-10-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbcuser',
            name='room_number',
            field=models.IntegerField(choices=[(101, '101'), (102, '102'), (103, '103'), (202, '202'), (211, '211')], null=True),
        ),
    ]
