# Generated by Django 2.1.2 on 2018-10-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='room_number',
            field=models.IntegerField(choices=[('101', '101'), ('102', '102'), ('103', '103'), ('202', '202')]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='year',
            field=models.IntegerField(choices=[('2', '2nd'), ('3', '3rd'), ('4', '4th')]),
        ),
    ]
