# Generated by Django 2.1.2 on 2019-01-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20181125_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbcuser',
            name='room_number',
            field=models.IntegerField(choices=[(101, '101'), (102, '102'), (103, '103'), (104, '104'), (105, '105'), (201, '201'), (202, '202'), (203, '203'), (204, '204'), (205, '205'), (207, '207'), (208, '208'), (209, '209'), (210, '210'), (211, '211'), (212, '212'), (301, '301'), (302, '302'), (303, '303'), (304, '304'), (305, '305'), (306, '306'), (307, '307'), (308, '308'), (309, '309'), (310, '310'), (311, '311'), (312, '312'), (400, 'Type IV')], null=True, verbose_name='room_number'),
        ),
        migrations.AlterField(
            model_name='rbcuser',
            name='year',
            field=models.IntegerField(choices=[(2, '2nd'), (3, '3rd'), (4, '4th'), (5, 'M.Tech 1st'), (6, 'M.Tech 2st')], null=True, verbose_name='year'),
        ),
    ]
