# Generated by Django 2.1.2 on 2018-10-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_remove_rbcuser_veg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rbcuser',
            name='email',
        ),
        migrations.AlterField(
            model_name='rbcuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
