# Generated by Django 2.1.2 on 2018-10-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_rbcuser_authenticate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rbcuser',
            old_name='authenticate',
            new_name='authenticated',
        ),
    ]
