# Generated by Django 2.1.2 on 2018-10-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_auto_20181019_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rbcuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
