# Generated by Django 2.1.2 on 2018-10-20 09:42

import Account.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_auto_20181020_1058'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='rbcuser',
            managers=[
                ('objects', Account.models.RBCUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='rbcuser',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_joined'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rbcuser',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='rbcuser',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
        migrations.AlterField(
            model_name='rbcuser',
            name='authenticated',
            field=models.BooleanField(default=False, verbose_name='authenticated'),
        ),
        migrations.AlterField(
            model_name='rbcuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='rbcuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='rbcuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='middle_name'),
        ),
        migrations.AlterField(
            model_name='rbcuser',
            name='room_number',
            field=models.IntegerField(choices=[(101, '101'), (102, '102'), (103, '103'), (202, '202'), (211, '211')], null=True, verbose_name='room_number'),
        ),
        migrations.AlterField(
            model_name='rbcuser',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='staff'),
        ),
        migrations.AlterField(
            model_name='rbcuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='rbcuser',
            name='year',
            field=models.IntegerField(choices=[(2, '2nd'), (3, '3rd'), (4, '4th')], null=True, verbose_name='year'),
        ),
    ]
