# Generated by Django 2.1.2 on 2018-10-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_auto_20181020_1512'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='rbcuser',
            managers=[
            ],
        ),
    ]
