# Generated by Django 2.1.2 on 2018-10-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_auto_20181020_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rbcuser',
            name='date_joined',
        ),
    ]
