# Generated by Django 2.1.2 on 2018-10-14 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image_scroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_description', models.CharField(max_length=100)),
                ('Image_height', models.IntegerField(blank=True, default='300', editable=False, help_text='300', null=True)),
                ('Image_width', models.IntegerField(blank=True, default='700', editable=False, help_text='700', null=True)),
                ('Images_scroll', models.ImageField(height_field='image_height', upload_to='Mess/Images/', width_field='image_width')),
                ('Image_comment', models.CharField(default='RBC Hall Mess', max_length=100)),
                ('Image_priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='secretary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.CharField(choices=[('secretary', 'secretary'), ('Asst.secretary', 'Asst.secretary')], max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('Image_height', models.IntegerField(blank=True, default='100', editable=False, help_text='100', null=True)),
                ('Image_width', models.IntegerField(blank=True, default='100', editable=False, help_text='100', null=True)),
                ('photo', models.ImageField(height_field='image_height', upload_to='Mess/Images/', width_field='image_width')),
                ('email', models.EmailField(default='', max_length=254)),
                ('PhoneNo', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 13 digits allowed.", regex='^\\+?1?\\d{10,13}$')])),
            ],
        ),
    ]
