version: 2
jobs:
  build:
    branches:
      only:
        - circlci
        - master
        - production
        - new

    working_directory: /srv/www/rbc
    docker:
      - image: circleci/python:3.6.4
#        environment:
#          PIPENV_VENV_IN_PROJECT: true
#    steps:
#      - checkout
#      - run: 
#         name: Change ownership to circleci user
#         command: |
#            sudo chown -R circleci:circleci /usr/local/bin
#            sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
#     - run:
#          name: Updating apt and install Ansible and pipenv
#         command: |
#            sudo yum update
#            sudo pip install ansible
#            sudo pip install pipenv
#            pipenv install
#      - run:
#          name: Simulate Django Migrations and Unit test
#          command: |
#           
#            pipenv run "python manage.py migrate"
#            pipenv run "python manage.py test"
#            
#      - run:
#        name: Merge master branch to prod
#         command: |
#            if [ "$CIRCLE_BRANCH" == "master" ];
#            then
#             git config user.email "rbchall.official@gmail.com" ;
#             git config user.name "rbchall" ;
#             git checkout production ;
#             git rebase master ;
#             git push origin production ; 
#            fi
#      - run:
#          name: Deploy to production if branch production
#          command: |
#            if [ "$CIRCLE_BRANCH" == "production" ];
#            then
#              cd deploy ;
#              ansible -i hosts  prod -m ping  -u ubuntu ;
#              ansible-playbook -i hosts  deploy.yml -u ubuntu  ;
#            fi
