# Generated by Django 2.1.2 on 2018-10-27 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AAA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.CharField(choices=[('Accoglienza', 'Accoglienza'), ('Alfresco', 'Alfresco'), ('Alvida', 'Alvida')], max_length=20, null=True)),
                ('description', models.TextField(max_length=255)),
                ('url', models.URLField(blank=True, help_text="if a page exists for the event then enter or leave '#' ", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('Hostel_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Hostel_short', models.CharField(default='', max_length=10)),
                ('slug', models.SlugField(default='', help_text='enter the filed with hostel short as RBC', max_length=10, unique=True)),
                ('Hostel_Email', models.EmailField(default='', max_length=254)),
                ('PhoneNo', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 13 digits allowed.", regex='^\\+?1?\\d{10,13}$')])),
                ('Hostel_startdate', models.DateField()),
                ('image_height', models.IntegerField(blank=True, default='100', editable=False, help_text='100', null=True)),
                ('image_width', models.IntegerField(blank=True, default='100', editable=False, help_text='100', null=True)),
                ('Hostel_logo', models.ImageField(height_field='image_height', upload_to='Hostel/Logo/', width_field='image_width')),
                ('Hostel_description', models.TextField()),
                ('Description_for_seo', models.TextField(blank=True, help_text='Decription of page for seo', max_length=255, null=True)),
                ('author_of_page', models.CharField(blank=True, max_length=25, null=True)),
                ('Facebook', models.URLField(default='https://www.facebook.com/Rishi-Bankim-Chandra-HallKGEC-105289579543000/', help_text='url to facebook page, default = https://www.facebook.com/Rishi-Bankim-Chandra-HallKGEC-105289579543000/ ')),
                ('Twitter', models.URLField(default='https://twitter.com/kgecrbchall', help_text='twitter link, default = https://twitter.com/kgecrbchall')),
                ('Google_Plus', models.URLField(default='https://plus.google.com/u/5/', help_text='google+ default url:- https://plus.google.com/u/5/')),
                ('Youtube', models.URLField(default='https://www.youtube.com/channel/UC3JOr-Opub8GRKwJjktqZtA', help_text='youtube channel default:-https://www.youtube.com/channel/UC3JOr-Opub8GRKwJjktqZtA')),
            ],
        ),
        migrations.CreateModel(
            name='HostelImgScroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_description', models.CharField(max_length=100)),
                ('image_height', models.IntegerField(blank=True, default='1080', editable=False, help_text='prefered: 1080', null=True)),
                ('image_width', models.IntegerField(blank=True, default='1900', editable=False, help_text='prefered: 1900', null=True)),
                ('Images_scroll', models.ImageField(height_field='image_height', upload_to='Hostel/Images/', width_field='image_width')),
                ('Image_comment', models.CharField(default='KGEC', help_text='for SEO', max_length=100)),
                ('Image_priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Hostel/Images/')),
                ('image_description', models.CharField(max_length=100)),
                ('image_slug', models.CharField(default='R.B.C Hall', help_text='slug to identify image for seo, keep different', max_length=10)),
            ],
        ),
    ]
