# Generated by Django 2.1.2 on 2018-10-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='Hostel_short',
            field=models.CharField(default='', max_length=10),
        ),
    ]
