# Generated by Django 2.1.2 on 2019-01-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aaa',
            name='Event_Image',
            field=models.ImageField(blank=True, null=True, upload_to='AAA/'),
        ),
        migrations.AddField(
            model_name='aaa',
            name='Image_Comment',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
