# Generated by Django 2.1.2 on 2018-10-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hostel_hostel_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='slug',
            field=models.SlugField(default='', help_text='enter the filed with hostel short as RBC', max_length=10, unique=True),
        ),
    ]
