# Generated by Django 2.1.2 on 2018-10-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hostel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel_img_scroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_description', models.CharField(max_length=100)),
                ('Images_scroll', models.ImageField(height_field=300, upload_to='Hostel/Images/', width_field=700)),
                ('Image_comment', models.CharField(default='KGEC', max_length=100)),
                ('Image_priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='Hostel_Images',
        ),
    ]
