# Generated by Django 2.1.2 on 2019-01-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190108_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaa',
            name='Event_Image',
            field=models.ImageField(default='image.png', upload_to='AAA/'),
        ),
    ]
