# Generated by Django 2.1.2 on 2018-10-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181013_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='height',
            field=models.PositiveIntegerField(default='150', verbose_name='150'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='width',
            field=models.PositiveIntegerField(default='500', verbose_name='500'),
        ),
        migrations.AddField(
            model_name='hostel_img_scroll',
            name='height',
            field=models.PositiveIntegerField(default='300', verbose_name='300'),
        ),
        migrations.AddField(
            model_name='hostel_img_scroll',
            name='width',
            field=models.PositiveIntegerField(default='700', verbose_name='700'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='Hostel_logo',
            field=models.ImageField(height_field='height', upload_to='Hostel/Logo/', width_field='width'),
        ),
        migrations.AlterField(
            model_name='hostel_img_scroll',
            name='Images_scroll',
            field=models.ImageField(height_field='height', upload_to='Hostel/Images/', width_field='width'),
        ),
    ]
