# Generated by Django 2.1.2 on 2018-10-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181013_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='height',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='width',
        ),
        migrations.RemoveField(
            model_name='hostel_img_scroll',
            name='height',
        ),
        migrations.RemoveField(
            model_name='hostel_img_scroll',
            name='width',
        ),
        migrations.AddField(
            model_name='hostel',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, help_text='100', null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, help_text='100', null=True),
        ),
        migrations.AddField(
            model_name='hostel_img_scroll',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='300', editable=False, help_text='300', null=True),
        ),
        migrations.AddField(
            model_name='hostel_img_scroll',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='700', editable=False, help_text='700', null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='Hostel_logo',
            field=models.ImageField(height_field='image_height', upload_to='Hostel/Logo/', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='hostel_img_scroll',
            name='Images_scroll',
            field=models.ImageField(height_field='image_height', upload_to='Hostel/Images/', width_field='image_width'),
        ),
    ]
