# Generated by Django 2.1.2 on 2018-10-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181013_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='image_height',
            field=models.IntegerField(blank=True, default='100', editable=False, help_text='100', null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='image_width',
            field=models.IntegerField(blank=True, default='100', editable=False, help_text='100', null=True),
        ),
        migrations.AlterField(
            model_name='hostel_img_scroll',
            name='image_height',
            field=models.IntegerField(blank=True, default='300', editable=False, help_text='300', null=True),
        ),
        migrations.AlterField(
            model_name='hostel_img_scroll',
            name='image_width',
            field=models.IntegerField(blank=True, default='700', editable=False, help_text='700', null=True),
        ),
    ]
