# Generated by Django 2.1.2 on 2018-10-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_image_upload_image_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hostel_img_scroll',
            new_name='HostelImgScroll',
        ),
        migrations.RenameModel(
            old_name='image_upload',
            new_name='ImageUpload',
        ),
    ]
