# Generated by Django 2.1.2 on 2018-10-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20181020_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='Background',
            field=models.ImageField(default=models.ImageField(height_field='image_height', upload_to='Hostel/Logo/', width_field='image_width'), upload_to='Hostel/img/'),
        ),
    ]
