# Generated by Django 2.1.2 on 2018-10-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_hostel_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='Background',
        ),
    ]
