# Generated by Django 2.1.2 on 2018-10-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_hostel_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='Hostel_description_for_seo',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='author',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
