# Generated by Django 2.1.2 on 2018-10-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20181022_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='author',
            new_name='author_of_page',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='Hostel_description_for_seo',
        ),
        migrations.AddField(
            model_name='hostel',
            name='Description_for_seo',
            field=models.TextField(blank=True, help_text='Decription of page for seo', max_length=15, null=True),
        ),
    ]
