# Generated by Django 2.1.2 on 2018-10-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20181022_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelimgscroll',
            name='Image_comment',
            field=models.CharField(default='KGEC', help_text='for SEO', max_length=100),
        ),
        migrations.AlterField(
            model_name='hostelimgscroll',
            name='image_height',
            field=models.IntegerField(blank=True, default='1080', editable=False, help_text='prefered: 1080', null=True),
        ),
        migrations.AlterField(
            model_name='hostelimgscroll',
            name='image_width',
            field=models.IntegerField(blank=True, default='1900', editable=False, help_text='prefered: 1900', null=True),
        ),
    ]
