# Generated by Django 2.1.2 on 2018-10-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20181022_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='AAA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.CharField(choices=[('Accoglienza', 'Accoglienza'), ('Alfresco', 'Alfresco'), ('Alvida', 'Alvida')], max_length=20, null=True)),
                ('priority', models.IntegerField(choices=[(1, 'Accoglienza'), (2, 'Alfresco'), (3, 'Alvida')], default=models.CharField(choices=[('Accoglienza', 'Accoglienza'), ('Alfresco', 'Alfresco'), ('Alvida', 'Alvida')], max_length=20, null=True))),
                ('description', models.TextField(max_length=255)),
                ('url', models.URLField(default='#', help_text="if a page exixts for the event then enter or leave '#' ")),
            ],
        ),
    ]
