# Generated by Django 2.1.2 on 2018-10-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_aaa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaa',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Accoglienza'), (2, 'Alfresco'), (3, 'Alvida')], verbose_name=models.CharField(choices=[('Accoglienza', 'Accoglienza'), ('Alfresco', 'Alfresco'), ('Alvida', 'Alvida')], max_length=20, null=True)),
        ),
    ]
