# Generated by Django 2.1.2 on 2018-10-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20181023_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaa',
            name='priority',
            field=models.IntegerField(verbose_name=((1, 'Accoglienza'), (2, 'Alfresco'), (3, 'Alvida'))),
        ),
    ]
