# Generated by Django 2.1.2 on 2018-10-23 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20181023_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aaa',
            name='priority',
        ),
    ]
