# Generated by Django 2.1.2 on 2018-10-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_aaa_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaa',
            name='url',
            field=models.URLField(blank=True, help_text="if a page exixts for the event then enter or leave '#' ", null=True),
        ),
    ]
