# Generated by Django 2.1.2 on 2018-10-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20181023_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaa',
            name='url',
            field=models.URLField(blank=True, help_text="if a page exists for the event then enter or leave '#' ", null=True),
        ),
    ]
