# Generated by Django 2.1.2 on 2018-10-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20181023_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aaa',
            name='Event',
        ),
        migrations.AddField(
            model_name='aaa',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Accoglienza'), (2, 'Alfresco'), (3, 'Alvida')], default=1),
        ),
    ]
