# Generated by Django 2.1.2 on 2018-10-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20181023_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aaa',
            name='priority',
        ),
        migrations.AddField(
            model_name='aaa',
            name='Event',
            field=models.CharField(choices=[('Accoglienza', 'Accoglienza'), ('Alfresco', 'Alfresco'), ('Alvida', 'Alvida')], max_length=20, null=True),
        ),
    ]
