# Generated by Django 2.1.2 on 2018-10-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20181023_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='aaa',
            name='priority',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
