# Generated by Django 2.1.2 on 2018-10-23 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_aaa_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aaa',
            name='priority',
        ),
    ]
