# Generated by Django 2.1.2 on 2018-10-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_aaa_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaa',
            name='priority',
            field=models.IntegerField(editable=False),
        ),
    ]
