# Generated by Django 2.1.2 on 2018-10-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20181023_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaa',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
