# Generated by Django 2.1.2 on 2018-10-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20181023_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaa',
            name='priority',
            field=models.IntegerField(default=3),
        ),
    ]
