# Generated by Django 2.1.2 on 2018-10-23 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20181023_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aaa',
            name='priority',
        ),
    ]
